# Generated by Django 5.2.17 on 2026-08-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPnlRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("realized_pnl", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "일일 실현손익",
                "verbose_name_plural": "일일 실현손익",
            },
        ),
    ]
